### ISSUE TITLE
Add gofmt check to test target in makefile

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/security-api-gateway#56]
The makefile should have in the `test` target a check to ensure that all the go code is formatted using `gofmt`. See example:

```make
test:
	$(GO) test ./... -cover
	$(GO) vet ./...
	gofmt -l .
	[ "`gofmt -l .`" = "" ] 
```

although here we don't have any go unit tests here but the latter statements should at least be there.

In the same PR the code will also need to be formatted with `gofmt`.

**Comment by lenny-intel** [comment]
@anonymouse64 , so you are good with "-w" ? ;-)

**Comment by anonymouse64** [comment]
whoops no I just copied what you had in your PR's...

**Comment by lenny-intel** [comment]
Issue should also include running gofmt to make sure all files are formatted so verify jobs will pass. ;-)

**Comment by tingyuz** [comment]
Fixed in #66 .

**Comment by anonymouse64** [comment]
@tingyuz please do not close issues until the issue is actually merged and fixed in master, i.e. your linked PR may eventually resolve the issue but it is not yet resolved because that PR hasn't been merged.
